---
galaxy_info:
  author: Oracle DBA Automation
  description: Sync Oracle alert, listener, and audit logs to NFS share
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: AIX
      versions:
        - all
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - oracle
    - database
    - logging
    - nfs
    - aix

dependencies: []
